### ISSUE TITLE
Enhancement request: per-environment headers

### ISSUE THREAD

**Issue by karmajunkie** [redound/graphql-ide#11]
I typically have headers that vary on a per-environment basis, e.g. JWT auth tokens that are use different keys between dev, staging and prod. It would be a great enhancement to be able to add these to the environment, which right now allows for setting variables but not the headers.

Many thanks for the hard work!

**Comment by olivierandriessen** [comment]
@karmajunkie Hi, Since 1.1 it's possible to set headers on the environment level. Although I think in your case project level headers would be enough if the handling is the same on each environment. You could for example add the header `Authorization: {{authToken}}` to the project and set the `authToken` variable with a different token value on each environment.

**Comment by karmajunkie** [comment]
Ahh, I see, I misunderstood the role of variables here. I was thinking that they were used as defaults for the graphql variables. I might suggest a link to some documentation around that or something, but otherwise I see now how to accomplish what I was looking for.  I'll close this, thanks again.
