### ISSUE TITLE
Headers don't seem to get persisted

### ISSUE THREAD

**Issue by hardchor** [redound/graphql-ide#2]
Hey,

When I change between saved queries or reload the app (CMD+R), any set headers seem to disappear. This is not the case for saved variables.

before:
<img width="1394" alt="screen shot 2016-11-26 at 14 21 36" src="https://cloud.githubusercontent.com/assets/307162/20640897/b11603ec-b3e3-11e6-9457-7a296a90439f.png">

after switching:
<img width="1390" alt="screen shot 2016-11-26 at 14 20 11" src="https://cloud.githubusercontent.com/assets/307162/20640887/86afa31a-b3e3-11e6-9571-c9f69ba0c8a7.png">

**Comment by olivierandriessen** [comment]
@hardchor hey, that shouldnt be the case. i will update this today.

**Comment by hardchor** [comment]
It seems to be intermittent - one of my 4 saved queries now persits the header!

**Comment by olivierandriessen** [comment]
@hardchor That's right, the headers get stored alongside the query. So you can store different queries with different headers. I'm planning some updates and I realised after I saw this issue that this isn't the expected behaviour and I think is better to store the headers on the project level. I think in general queries will all have the same headers except for a few in some cases. What do you think. Then enabling/disabling headers using a checkbox would make it easier to just disable a few headers for a given query. 

I also noticed storing queries won't work always as expected the way it's set up now, that will also be part of the coming updates.

**Comment by hardchor** [comment]
You're right, apologies! User error ;)
Having used https://github.com/skevy/graphiql-app before, I was used to the headers just getting persisted without pressing "save".
