### ISSUE TITLE
I can't change endpoints

### ISSUE THREAD

**Issue by sibelius** [redound/graphql-ide#6]
![image](https://cloud.githubusercontent.com/assets/2005841/20833314/2dc462c6-b876-11e6-91d2-8dae4bbee783.png)

it gets pink and do not change the endpoint

**Comment by olivierandriessen** [comment]
@sibelius Since 0.1.4 it should be fixed.

**Comment by sibelius** [comment]
tks, can u add support to homebrew to make upgrades easier?

**Comment by olivierandriessen** [comment]
@sibelius Will look into auto-updates when I have time.

**Comment by sibelius** [comment]
I've just updated and lost all my projects and query history

**Comment by olivierandriessen** [comment]
Since it's in heavy development data structures will change and due to available time I won't be writing migrations until it's stable. In case you're using MacOS, You can copy projects / queries files from /Users/<username>/Library/Application Support/graphiql-app to /Users/<username>/Library/Application Support/graphql-ide and it should work.
